import type { Metadata } from "next";
import { Russo_One, Exo_2, Orbitron } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import SiteBackdrop from "./components/SiteBackdrop";

const russoOne = Russo_One({
  variable: "--font-russo",
  subsets: ["latin"],
  weight: "400",
});

const orbitron = Orbitron({
  variable: "--font-orbitron",
  subsets: ["latin"],
  weight: ["500", "700", "900"],
});

const exo2 = Exo_2({
  variable: "--font-exo",
  subsets: ["latin"],
  weight: ["500", "700", "800"],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${russoOne.variable} ${exo2.variable} ${orbitron.variable} h-full antialiased`}
    >
      <body className="relative flex min-h-dvh flex-col bg-[#020108] font-[family-name:var(--font-exo)] text-[#ece8ff]">
        {/* Site-wide nebula, behind every page */}
        <SiteBackdrop />

        {/* Website content */}
        <div className="relative z-30 flex min-h-dvh flex-col">
          <Navbar />

          <main className="flex-1 flex flex-col">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}